apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data
spec:
  accessModes:
    - ReadWriteOnce 
  volumeMode: Filesystem
  storageClassName: "ccn-powerstore"
  resources:
    requests:
      storage: 100Gi
